# Config file needed only for the filters which model non-linear dynamics via smd
[general]
output_path = "./test_output/" # Defines the output directory. Use "./" to output to current working directory.
test_export = false # Set to true to export the test cases.

[VSOP87]
enabled = false
directory = "../smd/data/vsop87"

[SPICE]
enabled = true
directory = "../smd/cmd/refframes"
horizonDir = "../smd/data/horizon" # Files *must* be named to answer to fmt.Sprintf("%s-%04d", planetName, year) // TODO: Switch to a month too
horizonCSV = true # Set to False to compute each ephemeride separately
truncation = "1m" # Set to a Duration that can be parsed. Correspond to the truncation to use.
